export type VeterinarianCardType = {
  id: number;
  fullName: string;
  phone: string;
  image: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  slug: string;
  clinic_name: string;
  medical_license: string;
  license_type: string;
  license_image: string;
  national_id_image: string;
  issuance_date: string;
  bio: string;
  state: string;
  background_image: null | string;
  rate: number;
  surgery: number;
  experience: number;
  user: number;
  medical_center: number;
  province: { id: number; name: string };
  city: { id: number; name: string };
  lat: string;
  street:string;
  long: string;
};
